language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
  - nvm install v7.4.0
  - nvm use v7.4.0

script:
  - hexo generate
  - cd ./public
  - cat index.html

after_script:
  - cd ./public
  - git init
  - git config user.name "王晓勃"
  - git config user.email "wxb0328@icloud.com"
  - git add .
  - git commit -m "Update docs by wangxb"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/wxb/wxb.github.io.git